-- Supabase PostgreSQL Schema for Fitness Dashboard

CREATE TABLE workouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    split TEXT NOT NULL,
    exercise TEXT NOT NULL,
    sets INTEGER NOT NULL,
    reps INTEGER NOT NULL,
    weight REAL,
    rpe REAL,
    fatigue TEXT,
    duration INTEGER DEFAULT 0,
    set_data JSONB
);

CREATE TABLE steps (
    date DATE PRIMARY KEY,
    steps INTEGER NOT NULL,
    distance REAL,
    active_minutes INTEGER
);

CREATE TABLE food_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    food_item TEXT NOT NULL,
    calories INTEGER DEFAULT 0,
    protein INTEGER DEFAULT 0,
    carbs INTEGER DEFAULT 0,
    fats INTEGER DEFAULT 0,
    fiber INTEGER DEFAULT 0,
    meal_type TEXT DEFAULT 'Snack'
);

CREATE TABLE water_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    cups INTEGER DEFAULT 1
);

CREATE TABLE measurements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    weight REAL,
    waist REAL,
    hips REAL,
    thigh REAL,
    chest REAL,
    arms REAL
);

CREATE TABLE checkins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL,
    mood INTEGER DEFAULT 3,
    energy INTEGER DEFAULT 3,
    sleep_hours REAL,
    note TEXT
);

-- Note: We are not enabling Row Level Security (RLS) for now since this is a single-user personal dashboard.
-- If you plan to make this public or multi-user, you must enable RLS and add policies.
