begin;

alter table public.workouts
    add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.food_logs
    add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.water_logs
    add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.measurements
    add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.checkins
    add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.steps
    add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table public.steps drop constraint if exists steps_pkey;
alter table public.steps add column if not exists id bigint generated by default as identity;
alter table public.steps add primary key (id);

create index if not exists workouts_user_date_idx
    on public.workouts (user_id, date desc);
create index if not exists food_logs_user_date_idx
    on public.food_logs (user_id, date desc);
create index if not exists water_logs_user_date_idx
    on public.water_logs (user_id, date desc);
create index if not exists measurements_user_date_idx
    on public.measurements (user_id, date desc);
create index if not exists checkins_user_date_idx
    on public.checkins (user_id, date desc);
create unique index if not exists steps_user_date_key
    on public.steps (user_id, date);

commit;
